name: Merge Dev to Main

on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'
  workflow_dispatch:   # 수동으로 실행 가능

jobs: # 실행 작업 코드
  merge: # merge 실행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch # 'main' 브랜치로 branch checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: '0'

      - name: Configure Git # commit을 위한 git config 설정
        run: |
          git config user.name Whale0928
          git config user.email rlagusrl92@gmail.com

      - name: Merge dev branch # main 브랜치에서 dev 브랜치를 merge
        run: |
          git merge origin/dev --no-edit

      - name: Push changes to main branch # merge 내용들을 main 브랜치로 최종 push
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
