name: Merge Dev to Main

on:
  schedule:
    - cron: '0 0 * * MON' # 매주 월요일 0시에 실행
  workflow_dispatch:   # 수동으로 실행 가능

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
        # 메인 브랜치를 체크아웃

      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev
          path: dev
        # dev 브랜치를 체크아웃

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
        # Git 사용자 정보 설정

      - name: Merge dev into main
        run: |
          git checkout main
          git merge dev
        # dev 브랜치를 main 브랜치에 병합

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 변경 사항을 원격 저장소에 푸시
